version: '3.6'
services:
    mongo1:
        image: mongo:4.0.0
        command: mongod --replSet replicaTest --port 7011 --sslMode requireSSL --sslPEMKeyPassword certPass --sslPEMKeyFile /run/secrets/cert.pem --keyFile /run/secrets/MONGO_DB_KEYFILE
        ports:
            - 7011:7011
        volumes:
            - /data/disk1/mongo1/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        deploy:
            replicas: 1
            placement:
            constraints:
                - node.labels.mongo.replica == 1
        networks:
            - mongo
        secrets:
            - source: MONGO_DB_KEYFILE
                uid: '999'
                gid: '999'
                mode: 0600
            - cert.pem
    mongo2:
        image: mongo:4.0.0
        command: mongod --replSet replicaTest --port 7012 --sslMode requireSSL --sslPEMKeyPassword certPass --sslPEMKeyFile /run/secrets/cert.pem --keyFile /run/secrets/MONGO_DB_KEYFILE
        ports:
            - 7012:7012
        volumes:
            - /data/disk1/mongo1/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        deploy:
            replicas: 1
            placement:
            constraints:
                - node.labels.mongo.replica == 1
        networks:
            - mongo
        secrets:
            - source: MONGO_DB_KEYFILE
                uid: '999'
                gid: '999'
                mode: 0600
            - cert.pem
    mongo3:
        image: mongo:4.0.0
        command: mongod --replSet replicaTest --port 7013 --sslMode requireSSL --sslPEMKeyPassword certPass --sslPEMKeyFile /run/secrets/cert.pem --keyFile /run/secrets/MONGO_DB_KEYFILE
        ports:
            - 7013:7013
        volumes:
            - /data/disk1/mongo1/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        deploy:
            replicas: 1
            placement:
            constraints:
                - node.labels.mongo.replica == 1
        networks:
            - mongo
        secrets:
            - source: MONGO_DB_KEYFILE
                uid: '999'
                gid: '999'
                mode: 0600
            - cert.pem
    mongo4:
        image: mongo:4.0.0
        command: mongod --replSet replicaTest --port 7014 --sslMode requireSSL --sslPEMKeyPassword certPass --sslPEMKeyFile /run/secrets/cert.pem --keyFile /run/secrets/MONGO_DB_KEYFILE
        ports:
            - 7014:7014
        volumes:
            - /data/disk1/mongo1/db:/data/db
            - /etc/localtime:/etc/localtime:ro
        deploy:
            replicas: 1
            placement:
            constraints:
                - node.labels.mongo.replica == 1
        networks:
            - mongo
        secrets:
            - source: MONGO_DB_KEYFILE
                uid: '999'
                gid: '999'
                mode: 0600
            - cert.pem
networks:
    mongo:
secrets:
    MONGO_DB_KEYFILE:
        external: true
    cert.pem:
        external: true