version: '3.5'

networks:
  ghost: {}
  web:
    external: true

# volumes:
#   db:
#     driver: rexray/dobs
#     driver_opts:
#       size: 1
#   db-backup:
#     driver: rexray/dobs
#     driver_opts:
#       size: 1

secrets:
  db-password:
    file: ./secret-ghost-db


services:
  
  ghost:
    image: ghost:alpine
    networks:
      - web
      - ghost
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: YOURDBPASSWORDhere
      database__connection__database: ghost
      url: http://blog.localhost
    ports:
     - "2368:2368"
    volumes:
      - ../../data/devops/ghost/content:/var/lib/ghost/content
    labels:
      - traefik.port=2368
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:blog.localhost
    depends_on:
      - db
      - db-backup
    deploy:
      replicas: 1
      labels:
        - traefik.port=2368
        - traefik.docker.network=web
        - traefik.frontend.rule=Host:blog.localhost
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://127.0.0.1:5000"

  db:
    image: mysql:5.7
    volumes:
    #  - db:/var/lib/mysql
      - ../../data/devops/ghost/db:/var/lib/mysql
    secrets:
      - db-password
    networks:
      - ghost
    deploy:
      endpoint_mode: dnsrr
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://127.0.0.1:5000"

  db-backup:
    image: mysql:5.7
    command: sh -c "while true; do /usr/bin/mysqldump -u root --password=$$(< $$MYSQL_ROOT_PASSWORD_FILE) --all-databases --host=db > /backup/backup$$(date +'%H').sql ; sleep 3600; done"
    volumes:
    #  - db-backup:/backup
      - ../../data/devops/ghost/backupdb/:/backup
    secrets:
      - db-password
    networks:
      - ghost
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    deploy:
      restart_policy:
        delay: 600s
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://127.0.0.1:5000"

  #TODO: backup for static content
