#!/usr/bin/env bash
set -euo pipefail

get_build_env() {
  CI_SHA1=${CI_SHA1:-}
  CI_TAG=${CI_TAG:-}
  export GIT_HASH=${CI_SHA1:-"$(git rev-parse HEAD)"}
  export GIT_TAG=${CI_TAG:-"$(git tag --points-at ${GIT_HASH})"}
}

dev_init(){
    # at the project root add host folders
    mkdir secrets
    mkdir data
    mkdir data/devops
    mkdir data/devops/elasticsearch
    mkdir data/devops/elasticsearch/data 
    mkdir data/devops/portainer
    mkdir data/devops/ghost
    mkdir data/devops/ghost/backupdb
    mkdir data/devops/ghost/content
    mkdir data/devops/ghost/db
    # now do the initial build to pull images for devops
    cd devops
    docker-compose build
    cd ..
    # now do the initial build to pull images for devops
    cd develop
    docker-compose build
    cd ..
    docker network create web 
    docker network create mongo
}

ci_build_client(){
    # Get tags and hash
    get_build_env
    cd develop/apps/root-webapp
    npm install
    # Ensure code quality and tested
    npm run lint
    npm run test-headless
    npm run e2e
    # Do the build
    npm run build-prod    
}

$@
