version: '3.1'
services:
  cadvisor:
    container_name: cadvisor
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    labels: # labels here for compose-up and in deploy for swarm
    - traefik.port=8080
    - traefik.docker.network=proxy
    - traefik.frontend.rule=Host:advisor.localhost    
    # ports:
    #  - "8080:8080"
    networks:
      - proxy

networks:
  proxy:
    external: true