# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details#
version: 2
jobs:
  build-client:
    docker:
      - image: circleci/node:10.13.0-browsers-legacy
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "develop/apps/root-webapp/package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-
      - run: 
          name: CI build client
          command: ./cli ci_build_client    
      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "develop/apps/root-webapp/package.json" }}

workflows:
  version: 2
  build-deploy:
    jobs:
    - build-client:
    filters:
          branches:
            only: master
