# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details#
version: 2
jobs:
  build-client:
    docker:
      - image: circleci/node:10.13.0-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "develop/apps/root-webapp/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # Change to the client directory
      - run:
          name: 'Change dir to root-webapp'
          command: cd develop/apps/root-webapp      
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
    
      # Move most of the logic into a cli     
      # - run: 
      #     name: CI build client
      #     command: ./cli ci_build_client    
    
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "develop/apps/root-webapp/package.json" }}
          paths:
            - node_modules
      
      # Lint the source code
      - run:
          name: Linting
          command: npm run lint
      
      # Test the source code
      - run:
          name: Testing
          command: npm run test
      
      # Build project with different configuration based on
      # the current branch
      - run:
          name: Building
          command: |
              if [ "${CIRCLE_BRANCH}" == "staging" ]; then
                  npm run build-qa
              elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                  npm run build-prod
              else
                  npm run build-dev
              fi
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - dist
workflows:
  version: 2
  build:
    jobs:
      -  build-client

   